"""empty message

Revision ID: 50d45eadb20b
Revises: af00090d79a7
Create Date: 2025-10-15 18:24:49.688160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d45eadb20b'
down_revision = 'af00090d79a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.drop_column('model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
